# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{am-sendgrid}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Nelson"]
  s.date = %q{2010-01-23}
  s.email = %q{chris@gaslightsoftware.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/am-sendgrid.rb",
     "lib/smtp_api_header.rb",
     "test/am_sendgrid_test.rb",
     "test/helper.rb",
     "test/test_mailer/category_message.html.erb",
     "test/test_mailer/filter_message.html.erb"
  ]
  s.homepage = %q{http://github.com/sharespost/am-sendgrid}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Makes it easy to call the sendgrid SMTP api from ActionMailer}
  s.test_files = [
    "test/am_sendgrid_test.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionmailer>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
    else
      s.add_dependency(%q<actionmailer>, [">= 2.3.2"])
      s.add_dependency(%q<json_pure>, [">= 0"])
    end
  else
    s.add_dependency(%q<actionmailer>, [">= 2.3.2"])
    s.add_dependency(%q<json_pure>, [">= 0"])
  end
end

